version: '3.7'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
services:
  todo-web-application:
    image: in28min/todo-web-application-mysql:0.0.1-SNAPSHOT
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: prof_data
      RDS_USERNAME: vichu
      RDS_PASSWORD: vichu
    networks:
      - todo-web-application-network
	  # - web-application-mysql-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vichu
      MYSQL_ROOT_PASSWORD: vichu 
      MYSQL_USER: vichu
      MYSQL_PASSWORD: vichu
      MYSQL_DATABASE: prof_data
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
     - todo-web-application-network  
	#  - web-application-mysql-network
  
# Volumes
volumes:
  mysql-database-data-volume:

networks:
  todo-web-application-network: